#! /bin/sh
### BEGIN INIT INFO
# Provides:		      hd44780
# Required-Start:	   $local_fs $remote_fs $network $syslog
# Required-Stop: 	   $local_fs $remote_fs $network $syslog
# Should-Start: 	
# Default-Start:     2 3 4 5
# Default-Stop:		0 1 6  
# Short-Description:	HD44780 Infoscreen for squeezelite on a RPi
# Description:		   HD44780 Support on a Raspberry for squeezelite
#                    See: http://code.google.com/p/squeezelite/
#                    and: http://forums.slimdevices.com/showthread.php?
#                    Uninstall Instructions :
#                    service hd44780 stop
#                    update-rc.d hd44780 remove  
#                    rm /opt/hd44780/*.py
### END INIT INFO

DAEMON_SHELL="/usr/bin/python "
DAEMON_SCRIPT="/opt/hd44780/hd44780.py"
DAEMON=$DAEMON_SHELL" "$DAEMON_SCRIPT
DAEMON_NAME=hd44780
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid
lms=$(grep ^lms /opt/hd44780/config.py|cut -d "'" -f2)


do_start()
{
	#kill if already there
	echo "check 4 other running "$DAEMON_NAME" tasks" 
	for pID in $(ps aux |grep -v "grep"|grep $DAEMON |cut -d ' ' -f7)
	do
	    kill $pID
	done
	# start squeezelite if not already
	
	squeezelitepID=$(ps aux |grep -v 'grep'|grep 'squeezelite'|cut -d ' ' -f7)
	if [ "$squeezelitepID" = '' ]
	   then
	   service squeezelite start
	  sleep 2
	fi
	
	## make sure the network/logitechmediaserver is running
	## otherwise wait
	while ! ping -c1 $lms >/dev/null 2>&1
               do
               sleep 1
        done

	echo "Starting $DAEMON_NAME .."
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --exec $DAEMON
}
 
#
# Function that stops the daemon/service
#

do_stop()
{
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        #kill other instances from $DAEMON
        for pID in $(ps aux |grep -v "grep"|grep $DAEMON |cut -d ' ' -f7)
        do
        	kill $pID
        done
        #drop pidfile (just in case something was going wrong)
        ls /var/run/hd44780.pid >/dev/null 2>&1 && rm /var/run/hd44780.pid
}

do_check_connection()
{	
	traceroute 8.8.8.8 || sudo reboot
	gateway=$(traceroute 8.8.8.8|grep "^ 1"|cut -d " " -f4)
	while [ "$gateway" = '' ]
		do
	        	sleep 60
	        	traceroute 8.8.8.8 || sudo service networking stop && service networking start
	        done
	        

}
case "$1" in
  
    start|stop|check_connection)
        do_${1}
        ;;
    
   
    restart)
        do_stop
        do_start
        ;;
    
    status)
        . /lib/lsb/init-functions
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;                            
               
    state)
        backlight=$(python /opt/hd44780/lcd.py)
        echo $backlight
        ps aux |grep "/opt/hd44780/hd44780.py" |grep -v grep && (
               echo "hd44780 running" 
               exit 0) ||(
               echo "restart hd44780"
               service hd44780 start
               exit 1)                        
        ;;
     
    *) 
        echo "Usage: $SCRIPTNAME {start|stop|restart|status|check_connection}" >&2 
        exit 1
        ;;
esac

exit 0                              
